# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:alpine3.20
    restart: always
    networks:
      - apijwt
    volumes:
      - db-data:/var/lib/postgres/data
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: xboxmmvwwozldbbimvie
      # POSTGRES_USER: example
      # POSTGRES_DB: exampledb
    ports:
      - "5432:5432"

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  server:
    image: api-jwt-go
    environment:
      - exm=value
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - apijwt

networks:
  apijwt:
volumes:
  db-data:
