# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:alpine3.20
    restart: always
    volumes:
      - db-data:/var/lib/postgres/data
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: xboxmmvwwozldbbimvie
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    # network:
      # - db_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    # network:
      # - db_net

volumes:
  db-data:
# network:
  # db_net:

